### ISSUE TITLE
npm prune can remove some runtime dependencies

### ISSUE THREAD

**Issue by adborden** [goodeggs/travis-utils#2]
Some discussion here https://github.com/goodeggs/customers-api/commit/ec467e14118608632cc5fe75d7e1b83970ff4f32

This seems to be the behavior we're seeing:

> If your app has a dev dependency on module A, and a regular dependency on
> module B, which has a regular dependency on module A (compatible version),
> npm will only install the one at the top level, but then npm-production
> will strip it out because it's a dev dependency.

**Comment by adborden** [comment]
One idea is to be explicit, have two shrinkwraps (one for production, one for dev/test), and two caches. I know NPM can do some strange things. I believe this would be the foolproof way to avoid any npm magic, though not ideal to duplicate everything.

**Comment by makebbekus** [comment]
Another related case that bit us just yesterday:

We have a fixture file that uses `faker`. We sometimes uncomment a require statement to it locally to get some data in our local system. It's listed as a devDependency as it's never used in production; however, we accidentally committed the require statement uncommented. Travis tests and Ecru passed because they both install dev dependencies. Heroku crashed and burned.

Arguably, a smoke test would've caught this, but it's still frustrating to see a build make it that far with a simple "can't find `faker` error".

**Comment by demands** [comment]
@makebbekus I'm not sure I understand the issue here -- are you suggesting we should include `devDependencies` in our heroku buildpacks?

**Comment by makebbekus** [comment]
Nope. I'd just like to have the build fail before being deployed to heroku.
